name: Deploy to GitHub pages

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build web with PreTeXt
        uses: siefkenj/pretext-build-action@main
        with:
          pretext-command: build web
          project-root: "."
          output-dir: "."

      - name: Build print with PreTeXt
        uses: siefkenj/pretext-build-action@main
        with:
          pretext-command: build print
          project-root: "."
          output-dir: "."

      - name: Stage with PreTeXt
        uses: siefkenj/pretext-build-action@main
        with:
          pretext-command: deploy --stage-only
          project-root: "."
          output-dir: "."

      - name: Bundle output/stage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: output/stage

      - name: Bundle print output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: print
          path: output/print/main.pdf

      # Commit the print output to the feature branch
      # This step runs only if the current branch is not `main`.
      - name: Commit print output to feature branch
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add print PDF"
          file_pattern: "output/print/main.pdf"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "page"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
