name: Generate PDF and Commit to pdf-update

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build PDF with PreTeXt
        uses: siefkenj/pretext-build-action@main
        with:
          pretext-command: build print
          project-root: "."

      - name: Fetch and switch to main branch
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main

      - name: Create or update pdf-update branch from main
        run: git checkout -B pdf-update

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add output/print/main.pdf
          git commit -m "Update PDF" || echo "No changes to commit"

      - name: Force push to pdf-update branch
        run: git push origin pdf-update --force